// icons.js
// Единая база всех эмблем. Ключ = имя файла без .png.
// Путь всегда "assets/logos/<имя>.png"

window.ICONS = {
    "aek": "assets/logos/aek.png",
    "ajax": "assets/logos/ajax.png",
    "anderlecht": "assets/logos/anderlecht.png",
    "antwerp": "assets/logos/antwerp.png",
    "apoel": "assets/logos/apoel.png",
    "aston-villa": "assets/logos/aston-villa.png",
    "atalanta": "assets/logos/atalanta.png",
    "at-bilbao": "assets/logos/at-bilbao.png",
    "atm": "assets/logos/atm.png",
    "austria": "assets/logos/austria.png",
    "barca": "assets/logos/barca.png",
    "bayer": "assets/logos/bayer.png",
    "bayernm": "assets/logos/bayernm.png",
    "belgium": "assets/logos/belgium.png",
    "benfica": "assets/logos/benfica.png",
    "bayern": "assets/logos/bayern.png",
    "betis": "assets/logos/betis.png",
    "bologna": "assets/logos/bologna.png",
    "bournemouth": "assets/logos/bournemouth.png",
    "braga": "assets/logos/braga.png",
    "brentford": "assets/logos/brentford.png",
    "brighton": "assets/logos/brighton.png",
    "brugge": "assets/logos/brugge.png",
    "bvb": "assets/logos/bvb.png",
    "celta": "assets/logos/celta.png",
    "celtic": "assets/logos/celtic.png",
    "copenhagen": "assets/logos/copenhagen.png",
    "croatia": "assets/logos/croatia.png",
    "crystal-palace": "assets/logos/crystal-palace.png",
    "dynamo-kiev": "assets/logos/dynamo-kiev.png",
    "dynamo-zagreb": "assets/logos/dynamo-zagreb.png",
    "england": "assets/logos/england.png",
    "everton": "assets/logos/everton.png",
    "fenerbahce": "assets/logos/fenerbahce.png",
    "ferencvarosh": "assets/logos/ferencvarosh.png",
    "feyenoord": "assets/logos/feyenoord.png",
    "fiorentina": "assets/logos/fiorentina.png",
    "france": "assets/logos/france.png",
    "frankfurt": "assets/logos/frankfurt.png",
    "fulham": "assets/logos/fulham.png",
    "galatasaray": "assets/logos/galatasaray.png",
    "girona": "assets/logos/girona.png",
    "gladbach": "assets/logos/gladbach.png",
    "hajduk-split": "assets/logos/hajduk-split.png",
    "hoffenheim": "assets/logos/hoffenheim.png",
    "inter": "assets/logos/inter.png",
    "italy": "assets/logos/italy.png",
    "japan": "assets/logos/japan.png",
    "juventus": "assets/logos/juventus.png",
    "lazio": "assets/logos/lazio.png",
    "leeds-utd": "assets/logos/leeds-utd.png",
    "leicester": "assets/logos/leicester.png",
    "leipzig": "assets/logos/leipzig.png",
    "lens": "assets/logos/lens.png",
    "lille": "assets/logos/lille.png",
    "lion": "assets/logos/lion.png",
    "liverpool": "assets/logos/liverpool.png",
    "lokomotiv": "assets/logos/lokomotiv.png",
    "mallorca": "assets/logos/mallorca.png",
    "man-city": "assets/logos/man-city.png",
    "man-utd": "assets/logos/man-utd.png",
    "milan": "assets/logos/milan.png",
    "monaco": "assets/logos/monaco.png",
    "napoli": "assets/logos/napoli.png",
    "netherlands": "assets/logos/netherlands.png",
    "newcastle": "assets/logos/newcastle.png",
    "nice": "assets/logos/nice.png",
    "none": "assets/logos/none.png", // заглушка
    "norway": "assets/logos/norway.png",
    "nottingham-f": "assets/logos/nottingham-f.png",
    "olympiacos": "assets/logos/olympiacos.png",
    "o-marselle": "assets/logos/o-marselle.png",
    "osasuna": "assets/logos/osasuna.png",
    "panathinaikos": "assets/logos/panathinaikos.png",
    "paok": "assets/logos/paok.png",
    "porto": "assets/logos/porto.png",
    "portugal": "assets/logos/portugal.png",
    "psg": "assets/logos/psg.png",
    "psv": "assets/logos/psv.png",
    "rangers": "assets/logos/rangers.png",
    "real-madrid": "assets/logos/real-madrid.png",
    "real-sociedad": "assets/logos/real-sociedad.png",
    "roma": "assets/logos/roma.png",
    "salzburg": "assets/logos/salzburg.png",
    "scotland": "assets/logos/scotland.png",
    "sevilla": "assets/logos/sevilla.png",
    "shakhtar": "assets/logos/shakhtar.png",
    "slavia-praga": "assets/logos/slavia-praga.png",
    "southampton": "assets/logos/southampton.png",
    "spain": "assets/logos/spain.png",
    "sparta-praga": "assets/logos/sparta-praga.png",
    "sporting": "assets/logos/sporting.png",
    "spurs": "assets/logos/spurs.png",
    "steaua-b": "assets/logos/steaua-b.png",
    "stuttgart": "assets/logos/stuttgart.png",
    "switzerland": "assets/logos/switzerland.png",
    "torino": "assets/logos/torino.png",
    "trabzonspor": "assets/logos/trabzonspor.png",
    "twente": "assets/logos/twente.png",
    "udinese": "assets/logos/udinese.png",
    "union": "assets/logos/union.png",
    "valencia": "assets/logos/valencia.png",
    "venezia": "assets/logos/venezia.png",
    "victoria-plzen": "assets/logos/victoria-plzen.png",
    "villareal": "assets/logos/villareal.png",
    "wales": "assets/logos/wales.png",
    "werder": "assets/logos/werder.png",
    "westham-utd": "assets/logos/westham-utd.png",
    "wolfsburg": "assets/logos/wolfsburg.png",
    "wolves": "assets/logos/wolves.png",
    "yong-boys": "assets/logos/yong-boys.png",
    // --- LC Draft extra клубы (ключ = имя файла без .png) ---
    "alanyaspor": "assets/logos/alanyaspor.png",
    "antalyaspor": "assets/logos/antalyaspor.png",
    "arsenal": "assets/logos/arsenal.png",
    "augsburg": "assets/logos/augsburg.png",
    "az": "assets/logos/az.png",
    "basaksehir": "assets/logos/basaksehir.png",
    "basel": "assets/logos/basel.png",
    "besiktas": "assets/logos/besiktas.png",
    "bodo": "assets/logos/bodo.png",
    "brest": "assets/logos/brest.png",
    "brondby": "assets/logos/brondby.png",
    "burnley": "assets/logos/burnley.png",
    "cagliari": "assets/logos/cagliari.png",
    "cfr-cluj": "assets/logos/cfr-cluj.png",
    "chelsea": "assets/logos/chelsea.png",
    "como": "assets/logos/como.png",
    "elche": "assets/logos/elche.png",
    "espanyol": "assets/logos/espanyol.png",
    "famalicao": "assets/logos/famalicao.png",
    "freiburg": "assets/logos/freiburg.png",
    "gaziantep": "assets/logos/gaziantep.png",
    "genk": "assets/logos/genk.png",
    "genoa": "assets/logos/genoa.png",
    "gent": "assets/logos/gent.png",
    "getafe": "assets/logos/getafe.png",
    "hamburg": "assets/logos/hamburg.png",
    "koln": "assets/logos/koln.png",
    "lecce": "assets/logos/lecce.png",
    "lech-poznan": "assets/logos/lech-poznan.png",
    "legia": "assets/logos/legia.png",
    "levante": "assets/logos/levante.png",
    "lorient": "assets/logos/lorient.png",
    "lyon": "assets/logos/lyon.png",
    "mainz": "assets/logos/mainz.png",
    "malmo": "assets/logos/malmo.png",
    "marseille": "assets/logos/marseille.png",
    "metz": "assets/logos/metz.png",
    "midtjylland": "assets/logos/midtjylland.png",
    "moreirense": "assets/logos/moreirense.png",
    "nacional": "assets/logos/nacional.png",
    "paris-fc": "assets/logos/paris-fc.png",
    "parma": "assets/logos/parma.png",
    "rakow": "assets/logos/rakow.png",
    "rapid": "assets/logos/rapid.png",
    "rayo": "assets/logos/rayo.png",
    "real-oviedo": "assets/logos/real-oviedo.png",
    "rennes": "assets/logos/rennes.png",
    "rosenborg": "assets/logos/rosenborg.png",
    "samsunspor": "assets/logos/samsunspor.png",
    "santa-clara": "assets/logos/santa-clara.png",
    "sassuolo": "assets/logos/sassuolo.png",
    "standard": "assets/logos/standard.png",
    "steaua": "assets/logos/steaua.png",
    "strasbourg": "assets/logos/strasbourg.png",
    "sunderland": "assets/logos/sunderland.png",
    "toulouse": "assets/logos/toulouse.png",
    "union-sg": "assets/logos/union-sg.png",
    "utrecht": "assets/logos/utrecht.png",
    "viking": "assets/logos/viking.png",
    "vitoria-sc": "assets/logos/vitoria-sc.png",
    "young-boys": "assets/logos/young-boys.png"
  };
  
  // универсальный хелпер, чтобы везде использовать один и тот же вызов
  window.getLogoPath = function (key) {
    if (!key) return window.ICONS["none"] || "assets/logos/none.png";
  
    const normalized = String(key).trim().toLowerCase();
    if (window.ICONS[normalized]) {
      return window.ICONS[normalized];
    }
  
    // если нет такого ключа – подставляем заглушку
    return window.ICONS["none"] || "assets/logos/none.png";
  };
  